name: Variables DevOps

on: [push, workflow_dispatch]

env:
  PROYECTO: "Mi App aplicando Principios DevOps"
  AMBIENTE: "QA"

jobs:
  mostrar:
    runs-on: ubuntu-latest
    env:
      RESPONSABLE: "Estudiante DevOps"
    steps:
    - name: Mostrar info
      run: |
        echo "Proyecto: $PROYECTO"
        echo "Ambiente: $AMBIENTE"
        echo "Responsable: $RESPONSABLE"
